spring.application.name=finance-tracker

# URL ??????????? ? ???? ??????
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker

# ??? ???????????? PostgreSQL
spring.datasource.username=user

# ?????? ???????????? PostgreSQL
spring.datasource.password=

# ????????? ?????????? ?????? ??:
# update ? ????????? ??????? ??? ??????, ?? ?????? ??????
# create ? ??????????? ??????? ??? ?????? (?????? ????????!)
# validate ? ?????? ????????? ?????, ?? ????????
# none ? ?????? ?? ?????? (???????????? ? ??????????)
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL ??????? ??????? ?????????? Hibernate ? ???????
spring.jpa.show-sql=true

# ????????? open-in-view ? ??? ????? Spring ??????
# ?????????? ? ?? ???????? ?? ????? ?????????? ??????
# ??? ?????? ????????, ??????? ?????????
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

logging.level.org.springframework.web=DEBUG